server.port=8080
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.uri=http://localhost:8888
spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=vehicle-service
spring.cloud.gateway.routes[1].uri=lb://vehicle-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/vehicles/**

spring.cloud.gateway.routes[2].id=parking-space-service
spring.cloud.gateway.routes[2].uri=lb://parking-space-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/parking/**

spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=lb://payment-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**
